- uptime-service-backend/templates/deployment.yaml
- PM-854 Enable multi storage in helm chart
- PM-854 Add role session env var
- PM-854 Refactor initcontainer condition
- PM-854 Add variables to initcontainer and conditions to secrets
> PM 854 multi storage uptime service

- mina-daemon/README.md
- mina-daemon/scripts/entrypoint.sh
- mina-daemon/templates/deployment.yaml
- mina-daemon/values.yaml
This PR aims to retrieve an IP where the Mina Node can be reached from its peers as it currently live in a private network
> PM-1291 - Mina Daemon  Add DNS Discovery

- mina-payouts-data-provider/README.md
- mina-payouts-data-provider/values.yaml
- **PM-1338 - mina-payouts-data-provider - Update default tag**
> PM-1338 - mina-payouts-data-provider - Update default tag

- delegation-program-leaderboard/README.md
- delegation-program-leaderboard/values.yaml
A little generic note to point users where to find possible environment variables.
> PM-1405: update README how to add ENV vars

- mina-payouts-data-provider/values.yaml
Updating the default image as a hot fix was released
> PM 1542 deploy new version of mina data payout provider

- gpt-survey-summarizer/README.md
- gpt-survey-summarizer/templates/cronjob.yaml
- gpt-survey-summarizer/values.yaml
This is going to auto-cleanup the finished jobs
> PM-1570 Autocleanup for exporter jobs

- .pre-commit-config.yaml
- mina-payouts-data-provider/README.md
- mina-payouts-data-provider/values.yaml
Updating base image and implementing Readme through pre-commit
> Update Mina Payout Data Provider Readme + base image

- raw/.helmignore
- raw/Chart.yaml
- raw/README.md
- raw/ci/resources-values.yaml
- raw/ci/templates-values.yaml
- raw/ci/values.yaml
- raw/templates/_helpers.tpl
- raw/templates/resources.yaml
- raw/values.yaml
This chart is copied from archived now repository for us to be able to access it easier and not depend on it disappearing.
With this chart we can deploy in our releases loose additional k8s resources
> PM-1532 add raw helm chart to our helm charts

- .github/workflows/pre-commit.yaml
CI running pre-commit hooks to check on PRs and merges that the hooks were installed by the contributors
> PM-1643 Pre-commit CI

- gpt-survey-summarizer/README.md
- gpt-survey-summarizer/templates/deployment_bot.yaml
- gpt-survey-summarizer/templates/deployment_server.yaml
- gpt-survey-summarizer/values.yaml
Support for annotations on resources of type `Deployment`
> PM-1706 GSS deployment annotations

- .pre-commit-config.yaml
- liminal-manual/.helmignore
- liminal-manual/Chart.yaml
- liminal-manual/README.md
- liminal-manual/templates/NOTES.txt
- liminal-manual/templates/_helpers.tpl
- liminal-manual/templates/deployment.yaml
- liminal-manual/templates/hpa.yaml
- liminal-manual/templates/ingress.yaml
- liminal-manual/templates/service.yaml
- liminal-manual/templates/serviceaccount.yaml
- liminal-manual/values.yaml
This PR declares the helm chart for `liminal-manual`.
Used here: https://argo-cd.minaprotocol.tools/applications/argo-cd/production-liminal-manual.
> PM-1694 - Add liminal manual chart

- gpt-survey-summarizer/README.md
- gpt-survey-summarizer/templates/deployment_bot.yaml
- gpt-survey-summarizer/templates/deployment_server.yaml
- gpt-survey-summarizer/values.yaml
Adds GSS_LOG_LEVEL env variable to the helm chart.
> GSS Log Level

- mina-staking-ledgers-exporter/scripts/mina-staking-ledgers-exporter.py
The current changes work for both current and next staking ledger. However, I am unable to test this script on a non-ready next epoch staking ledger. We need to test it at the beginning of an epoch
> PM-1923 - Soft fail next epoch staking-ledger processing

- .pre-commit-config.yaml
- on-chain-voting/README.md
- on-chain-voting/templates/deployment-server.yaml
- on-chain-voting/templates/deployment-web.yaml
- on-chain-voting/values.yaml
This is the same chart as the previous one to the exception, if the `deploymentAnnotations` and the autogenerated ReadMe
> PM-1942 - Refactor on-chain-voting

- on-chain-voting/README.md
- on-chain-voting/values.yaml
- **PM-1942 - Update ocv server image repository**
> PM 1942 ocv split artifact into their own repository

- kyc-management-app/templates/ingress.yaml
- **PM-1888 - Fix KYC Ingress**
> PM 1888 create kyc management app helm chart

- kyc-management-app/templates/deployment.yaml
- **PM-1947 - KYC Add Database URL to deployment**
> PM-1947 - KYC Add Database URL to deployment

- kyc-management-app/templates/_helpers.tpl
- kyc-management-app/templates/deployment.yaml
- **PM-1951 - KYC - Add external database support**
- **PM-1951 - KYC - Remove postgres helper to accommodate external db**
> PM 1951 Remove postgres helper to accommodate external db

- mina-payout-reports/README.md
- mina-payout-reports/templates/deployment-api.yaml
- mina-payout-reports/values.yaml
addresses https://github.com/MinaFoundation/mina-payout-reports/pull/17 changes
> PM-1941 switch mina-payout-reports to s3 bucket for staking ledgers

- kyc-management-app/README.md
- kyc-management-app/values.yaml
- **PM-1972 - Kyc - Implement liveness and readiness**
- **PM-1972 - Kyc - Update base image**
> PM 1972 kyc implement liveness and readiness

- kyc-management-app/README.md
- kyc-management-app/values.yaml
- **PM-1984 - KYC - Add persitence on postgres by default**
- **PM-1984 - KYC - update base image to 0.1.25**
> PM 1984 kyc enable persitence on postgres by default

- mina-payouts-data-provider/README.md
- mina-payouts-data-provider/templates/deployment.yaml
- mina-payouts-data-provider/values.yaml
- **PM-2004 - Enable Lifecyle on DP Submission Report**
- **PM-2004 - Enable Lifecyle on Mina Data Payout Provider**
> PM 2004 enable lifecyle on deployments

- mina-daemon/templates/deployment.yaml
- **PM-485 - Mina Daemon - Exclude Liveness for snark-workers**
> PM-485 - Mina Daemon - Exclude Liveness for snark-workers

- kyc-management-app/Chart.lock
- kyc-management-app/Chart.yaml
- kyc-management-app/README.md
- **Add gcp sa secret to kyc**
- **Lock postgresql to a specific version**
> Add gcp sa secret to kyc

- web-terminal/.helmignore
- web-terminal/Chart.yaml
- web-terminal/README.md
- web-terminal/templates/NOTES.txt
- web-terminal/templates/_helpers.tpl
- web-terminal/templates/deployment.yaml
- web-terminal/templates/hpa.yaml
- web-terminal/templates/ingress.yaml
- web-terminal/templates/role.yaml
- web-terminal/templates/rolebinding.yaml
- web-terminal/templates/service.yaml
- web-terminal/templates/serviceaccount.yaml
- web-terminal/values.yaml
This PR implements a web-terminal to allow to open a shell via a web interface.
Shared https://governance-pgt-live-logs.minaprotocol.network with Illya for experimentation.
> PM-2097 - Add web-terminal helm chart
